### PR TITLE
agenda-view-componentつくった

### PR DESCRIPTION
**Pull request by gatchan0807**

### CODE REVIEW

**Comment by gatchan0807** [comment]
screenshot from 2017-10-22 02 06 57
screenshot from 2017-10-22 02 07 02
screenshot from 2017-10-22 02 07 06

**Comment by gatchan0807** [comment]
screenshot from 2017-10-22 02 10 14
screenshot from 2017-10-22 02 10 17

**Comment by gatchan0807** [comment]
修正後

**Comment by konojunya** [comment]
lgtm13

**Pull request merged**
